version: "2"
services:
  backend_latest:
    build:
      context: ../backend/.
      dockerfile: Dockerfile
    #image: nryabkov/myrepository:backend_latest
    #container_name: backend_latest
    ports:
      - 3006:3006
  frontend_latest:
    build:
      context: .
      dockerfile: Dockerfile
    #container_name: frontend_latest
    ports:
      - 80:80
      - 443:443
    links:
      - backend_latest
